version: '3.8'

services:
  mongo:
    image: mvertes/alpine-mongo:latest
    container_name: mongodb_chat_online
    restart: unless-stopped
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: chat_online
    volumes:
      - mongo_data_alpine:/data/db

volumes:
  mongo_data_alpine:
